apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: php-kubernetes-example

nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./
        containerPath: /project
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
