apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}

data:
  nginx-php.conf: |-
    server {
        listen 0.0.0.0:8080;

        root /var/www/html/public;

        location / {
          try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
          fastcgi_index        index.php;
          fastcgi_param        SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass         127.0.0.1:9000;
          include              fastcgi_params;
        }
    }
