apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include ".helm.fullname" . }}
                port:
                  number: 8080
